config:
  path: /opt/apache-zookeeper-3.7.0-bin/conf
  tickTime: 3000
  initLimit: 10  # tickTIme的倍数
  syncLimit: 5 # tickTIme的倍数
  clientPort: 2181
  maxClientCnxns: 60 # 单个客户端对单个ZK服务器的连接数限制，如果为0则不限制
  dataDir: /tmp/zookeeper
  commands_whitelist: "*"
  # dataLogDir: 
  # autopurge:
  #   snapRetainCount: 3
  #   purgeInterval: 0
  # metricsProvider:
  #   className: org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider
  #   httpPort: 7000
  #   exportJvmInfo: false

# 副本数量
replicaCount: 3
podManagementPolicy: Parallel
image: registry.cn-shenzhen.aliyuncs.com/xkj-jx/zookeeper:3.7.0
imagePullPolicy: Always
# 资源限制
# resources:
# 环境变量
# env:

# 注解
# podAnnotations:
#   key: value

# 名称，默认为zookeeper
# nameOverride: zookeeper

service:
  type: NodePort

storage:
  enabled: true
  storageClassName: ""
  size: 1Gi

  logStorage:
    enabled: false
    storageClassName: ""
    size: 1Gi