config:
  path: /opt/apache-zookeeper-3.7.0-bin/conf
  tickTime: 2000
  initLimit: 10
  syncLimit: 5
  clientPort: 2181
  maxClientCnxns: 60
  # autopurge:
  #   snapRetainCount: 3
  #   purgeInterval: 0
  # metricsProvider:
  #   className: org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider
  #   httpPort: 7000
  #   exportJvmInfo: false

# 副本数量
replicaCount: 3
# podManagementPolicy: OrderedReady
image: registry.cn-shenzhen.aliyuncs.com/xkj-jx/zookeeper:3.7.0
imagePullPolicy: Always
# 资源限制
# resources:
# 环境变量
# env:

# 注解
# podAnnotations:
#   key: value

# 名称，默认为zookeeper
# nameOverride: zookeeper